====================
Errors and solutions
====================

The first actions you should do !
=================================

.. epigraph::

    Dammit, my Domogik system is not working, how can I solve my issue ?

    -- From you, who are reading this page 

First don't forget to :

* check the log files for errors
* check the process status 
* check if services are availables
* check if xPL is working fine

Check the log files
-------------------

Log files are available in :

* **/var/log/domogik/** for Domogik
* **/var/log/xplhub/** for the python xPL hub

You an find all the errors with this command: ::

    $ grep ERROR /var/log/domogik/*

Example: ::

    /var/log/domogik/manager.log:2013-12-06 14:35:24,371 domogik-manager ERROR Package plugin-onewire : invalid json file
    /var/log/domogik/manager.log:2013-12-06 14:35:24,371 domogik-manager ERROR Package plugin-onewire : Error validating the json: key 'xpl' not found in a param for device_type onewire.serial_number

Check the process status
------------------------

Assuming the Domogik user is *domogik*, do the following checks:

* check all main components are up: 

    ::

        $ ps -fu domogik | grep dmg_

    You must have one process for the *MQ broker* and one for the *MQ forwarder*: ::

        domogik    32562     1  1 14:12 ?        00:00:23 /usr/bin/python /usr/local/bin/dmg_broker
        domogik    32583     1  0 14:12 ?        00:00:00 /usr/bin/python /usr/local/bin/dmg_forwarder

    You must have one process for the python hub: ::

        domogik    32605     1  0 14:12 ?        00:00:06 /usr/bin/python /usr/local/bin/dmg_hub

    You must have 2 processes for the administration web interface: ::

        domogik      329     1  0 14:12 ?        00:00:00 /usr/bin/python /usr/local/bin/dmg_admin
        domogik      336   329  0 14:12 ?        00:00:06 /usr/bin/python /usr/local/bin/dmg_admin

    You must have 2 processes for the manager: ::

        domogik    32635     1  0 14:12 ?        00:00:00 /usr/bin/python /usr/local/bin/dmg_manager -d -r -x -s
        domogik    32642 32635  0 14:12 ?        00:00:09 /usr/bin/python /usr/local/bin/dmg_manager -d -r -x -s

    Check if rest is up: ::

        $ ps -fu fritz | grep rest
        fritz    32700     1  0 14:12 ?        00:00:00 /usr/bin/python /media/stock/domotique/git/domogik/src/domogik/bin/rest.pyc
        fritz    32709 32700  0 14:12 ?        00:00:12 /usr/bin/python /media/stock/domotique/git/domogik/src/domogik/bin/rest.pyc

    Check if dbmgr is up: ::

        $ ps -fu domogik | grep dbmgr
        domogik    32669     1  0 14:12 ?        00:00:00 /usr/bin/python /media/stock/domotique/git/domogik/src/domogik/bin/dbmgr.py
        domogik    32678 32669  0 14:12 ?        00:00:13 /usr/bin/python /media/stock/domotique/git/domogik/src/domogik/bin/dbmgr.py

    Check if xplgw is up: ::

        $ ps -fu domogik | grep xplgw
        domogik    32726     1  0 14:12 ?        00:00:00 /usr/bin/python /media/stock/domotique/git/domogik/src/domogik/bin/xplgw.py
        domogik    32735 32726  0 14:12 ?        00:00:13 /usr/bin/python /media/stock/domotique/git/domogik/src/domogik/bin/xplgw.py

    If one component is not up, check its log files. If the component is *rest*, *dbmgr* or *xplgw* and you find no logs, check in the *manager* logs.

Check if services are availables
--------------------------------

You can use the following command on your server to check all ports where a service is listening. Notice that Domogik uses by default ports in 404xx range. ::

    # netstat -tnpl | grep 404

If rest server is up, you will see: ::
    
    tcp        0      0 192.168.1.10:40405      0.0.0.0:*               LISTEN      32709/python

If the administration web interface is up, you will see (depending on your network configuration): ::
    
    tcp        0      0 192.168.1.10:40406      0.0.0.0:*               LISTEN      336/python
    tcp        0      0 127.0.0.1:40406         0.0.0.0:*               LISTEN      336/python

If message queue broket and forwarder are up, you will see: ::
    
    tcp        0      0 192.168.1.10:40410      0.0.0.0:*               LISTEN      32562/python
    tcp        0      0 192.168.1.10:40411      0.0.0.0:*               LISTEN      32583/python
    tcp        0      0 192.168.1.10:40412      0.0.0.0:*               LISTEN      32583/python

You can find more informations about the used ports in the :doc:`network ports page </technical/network_ports>`.


Check xPL is working fine
-------------------------

If you think xPL is not working, do: ::

    $ grep "HUB discovery" /var/log/domogik/xplgw.log

You should have the following lines: ::

    2013-12-06 14:12:23,435 domogik-xplgw INFO HUB discovery > starting
    2013-12-06 14:12:23,436 domogik-xplgw INFO HUB discovery > looking for the hub. I hope there is one hub, Domogik won't work without the hub!
    2013-12-06 14:12:23,438 domogik-xplgw INFO HUB discovery > Received HBEAT echo, HUB detected
    2013-12-06 14:12:23,438 domogik-xplgw INFO HUB discovery > hub found, configuration in progress

If the following lines appears always, it means that the xPL hub is not found. So you should check your configurationor network access (firewall, ...): ::

    2013-12-06 14:12:23,435 domogik-xplgw INFO HUB discovery > starting
    2013-12-06 14:13:33,436 domogik-xplgw INFO HUB discovery > looking for the hub. I hope there is one hub, Domogik won't work without the hub!
    2013-12-06 14:13:35,436 domogik-xplgw INFO HUB discovery > looking for the hub. I hope there is one hub, Domogik won't work without the hub!
    2013-12-06 14:13:37,436 domogik-xplgw INFO HUB discovery > looking for the hub. I hope there is one hub, Domogik won't work without the hub!
    2013-12-06 14:13:39,436 domogik-xplgw INFO HUB discovery > looking for the hub. I hope there is one hub, Domogik won't work without the hub!

The python xPL hub configuration is set in **/etc/domogik/xplhub.cfg**. The logs are in **/var/log/xplhub/**






Domogik 0.1/0.2/0.3 errors (that may still happen in 0.4)
=========================================================

libmysqlclient issue on Ubuntu 12.04
------------------------------------

Error: ::

    ImportError: libmysqlclient_r.so.16: cannot open shared object file: No such file or directory


Solution: 

    Ubuntu install the libmysqlclient in release 18. Just create a symlink: ::

        ln -v /usr/lib/i386-linux-gnu/libmysqlclient_r.so.18 /usr/lib/i386-linux-gnu/libmysqlclient_r.so.16





!!Browser
!!!My browser never ends loading the page
!!!!Error
The loading indicator of your browser never stops loading

!!!!Cause
This is not an error. Domogik always listen for events on the REST server so in fact loading never stops :)

!!xPL Hub
!!!xPL Hub doesn't start (C version) 
!!!!Error
When manualy launching the xPL Hub, you get :
{CODE()}
$ ./xPL_Hub                                                                       
bash: ./xPL_Hub: Aucun fichier ou dossier de ce type
{CODE}

!!!!Cause
You may be on a 64bits system with no 32bits glibc library

!!!!Solution
Install the 32bits glibc. Example for Archlinux :

{CODE()}
pacman -S lib32-glibc
{CODE}

!!Manager
!!!ConfigParser.NoSectionError: No section: 'domogik'  (v0.1)
!!!!Error
{CODE()}
...
ConfigParser.NoSectionError: No section: 'domogik'                              
Exception AttributeError: "__Singl_BasePlugin instance has no attribute '_log'" 
in <bound method __Singl_BasePlugin.__del__ of <domogik.xpl.common.baseplugin.__
Singl_BasePlugin instance at 0xc4ccb0>> ignored                                 
Exception AttributeError: "'NoneType' object has no attribute 'debug'" in <bound
 method __Singl_xPLPlugin.__del__ of None> ignored            
{CODE}

!!!!Cause
There is no ~/.domogik/domogik.cfg file or it has a bad format

!!!!Solution
Create or fix the problem in this file.

!!REST/RINOR
!!!REST doesn't start
!!!!Error
In rest.log you only get :
{CODE()}
2010-05-21 16:16:41,150 domogik-rest INFO Daemonize plugin rest
2010-05-21 16:16:41,151 domogik-rest DEBUG watcher fork
2010-05-21 16:16:41,151 domogik-rest DEBUG New system manager instance for rest
2010-05-21 16:16:41,152 domogik-rest DEBUG xPL plugin rest socket bound to 127.0.0.1, port 58975
2010-05-21 16:16:41,153 domogik-rest DEBUG New timer registered : <domogik.xpl.lib.xplconnector.xPLTimer> name : internal-timer
2010-05-21 16:16:41,154 domogik-rest DEBUG New listener, filter : {'xpltype': 'xpl-stat', 'schema': 'hbeat.app'}
2010-05-21 16:16:41,155 domogik-rest DEBUG xPL thread started for rest 
2010-05-21 16:16:41,155 domogik-rest DEBUG New listener, filter : {'xpltype': 'xpl-cmnd', 'schema': 'domogik.system'}
2010-05-21 16:16:41,155 domogik-rest DEBUG end single xpl plugin
2010-05-21 16:16:41,155 domogik-rest DEBUG after watcher
{CODE}

If you launch REST manually (./rest.py -f), you get :
{CODE()}
create Base plugin instance
new query
{CODE}

!!!!Cause
There are two possibilities : 
* The xPL Hub is not launched
* The Database Manager wasn't able to give REST his configuration

!!!!Solution
!!!!!The xPL Hub is not launched
Launch it. To check if it is started, run this command:
{CODE()}netstat -lun{CODE}
If you see a line displaying the port 3865 then it is running.

!!!!!The Database Manager wasn't able to give REST his configuration
Launch it manually (./dbmgr.py -f). Launch REST and see which error happens (see Database Manager section to see errors)

!!!REST doesn't start
!!!!Error
In stdout you get : 
{CODE()}
Traceback (most recent call last):
  File "/root/configure-hgrc/domogik/src/domogik/xpl/bin/rest.py", line 3839, in <module>
    rest_server.start_http()
  File "/root/configure-hgrc/domogik/src/domogik/xpl/bin/rest.py", line 444, in start_http
    handler_params = [self])
  File "/root/configure-hgrc/domogik/src/domogik/xpl/bin/rest.py", line 496, in __init__
    bind_and_activate)
TypeError: __init__() takes exactly 3 arguments (4 given)
{CODE}

!!!!Cause
REST is not compatible with python 2.5

!!!!Solution
Install python 2.6

!!!Rest /plugin/detail/<plugin name> makes xpl_hub (c version) crashes
!!!!Error
A /plugin/detail/cidmodem (for example) REST request makes xpl_hub crash in a __segmentation fault__

!!!!Cause
It happens only with the -xpldebug option for xpl_hub

!!!!Solution
Use the hub without -xpldebug option

!!!REST is slow
!!!!Error
For example, the config page of plugins takes more than 5 seconds to be displayed

!!!!Cause
Definitely due to DNS issue. Check rest.log times, especially the time between :
* domogik-rest DEBUG Send HTTP header for OK, and 
* domogik-rest DEBUG Send HTTP data : {...}
If the difference is something like 5s, your DNS setup may be bad.

!!!!Solution
If you have ''avahi'' running (at least on a Ubuntu Desktop install), it could be stopped unless you know that you need it. That should solve your problem.
If you don't have such software, check your DNS setup, one quick way to check (without using domogik) is to run the command :
<pre>
time getent hosts the.ip.of.client
</pre>
If it takes long time without any answer, your setup is wrong.

!!!!Solution with a karotz on the LAN
You must assign a host name to your Karotz on your local network.

!!Plugins
!!!Plugin don't start automatically
!!!!Error
After rebooting the server, plugins marked as "Automatically start plugin at Domogik startup" don't start.
Plugins start correctly after doing ''/etc/init.d/domogik restart''.
!!!!Cause
Domogik starts before mysql and doesn't load plugins.
!!!!Solution (Debian)
After the installation process, if you did:
{CODE()}update-rc.d -f domogik defaults{CODE}
It generates the following symlinks:
{CODE()}
/etc/rc1.d/K02domogik
/etc/rc2.d/S01domogik
/etc/rc3.d/S01domogik
/etc/rc4.d/S01domogik
/etc/rc5.d/S01domogik
{CODE}
Add ''mysql'' to the ''/etc/init.d/domogik'' :
{CODE()}# Required-Start: $local_fs $network *mysql*{CODE}
Now, these symlinks are generated :
{CODE()}
/etc/rc1.d/K02domogik
/etc/rc2.d/S20domogik
/etc/rc3.d/S20domogik
/etc/rc4.d/S20domogik
/etc/rc5.d/S20domogik
{CODE}
Mysql starts before domogik (S19) and all is OK.

!!!Plugin onewire and hardware usb issue
!!!!Error
All was working with 6 DS18B20 in parasite mode, i add 4 new one on the onewire bus (still in parasite mode) and starting having problems.
The plugin start correctly but stop working after few minutes or hours it depends.
Plugin is still working and still send xpl-stat command but no answer from the hardware (you could see that in the onewire.log file).

!!!!Cause
I use a simple usb hub without power supply, Teleinfo hardware, DS9490R Usb adaptor and a Mir:ror are powered on.
!!!!Solution
If you see some ttyusb error in dmesg don't look around it's a usb power problem. Removing the Mir:ror or adding a power supply on the Usb Hub remove the problem.

Now you can enjoy long time tracking without any hole.

